chore: update Go version to 1.26 and refine workflow paths; adjust resource hash list types (#696)

diff --git a/.github/workflows/test-and-build.yml b/.github/workflows/test-and-build.yml
--- a/.github/workflows/test-and-build.yml
+++ b/.github/workflows/test-and-build.yml
@@ -4,8 +4,8 @@ on:
     branches:
       - main
     paths:
-      - 'pkg/**'
-      - 'typescript/models/**'
+      - "pkg/**"
+      - "typescript/models/**"
       - go.mod
 jobs:
   build:
@@ -13,33 +13,33 @@ jobs:
       contents: read
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up Go
-      uses: actions/setup-go@v4
-      with:
-        go-version: '1.24'
-    - name: Cache Go modules
-      uses: actions/cache@v3
-      with:
-        path: /tmp/go-build-cache
-        key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}
-        restore-keys: |
-          ${{ runner.os }}-go-
-    
-    - name: Build
-      run: go build ./pkg/...
-    #TODO: Check if generator needs to be run, fail if the generator generates new files
-    - name: run generator
-      run: |
-        echo running generator...
-        go run cmd/generator/main.go
-        git diff --exit-code --numstat pkg/
-        if [ $? -ne 0 ]; then
-          echo "Generator generated new files, please run the generator locally and commit the changes"
-          exit 1
-        fi
-    - name: Test
-      run: |
+      - uses: actions/checkout@v3
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: "1.26"
+      - name: Cache Go modules
+        uses: actions/cache@v3
+        with:
+          path: /tmp/go-build-cache
+          key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}
+          restore-keys: |
+            ${{ runner.os }}-go-
+
+      - name: Build
+        run: go build ./pkg/...
+      #TODO: Check if generator needs to be run, fail if the generator generates new files
+      - name: run generator
+        run: |
+          echo running generator...
+          go run cmd/generator/main.go
+          git diff --exit-code --numstat pkg/
+          if [ $? -ne 0 ]; then
+            echo "Generator generated new files, please run the generator locally and commit the changes"
+            exit 1
+          fi
+      - name: Test
+        run: |
           echo testing...
           go get -t ./...
           go vet ./...
@@ -52,12 +52,12 @@ jobs:
       contents: read
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '22'
-    - name: Install dependencies
-      run: npm install
-    - name: Test
-      run: npm run build
+      - uses: actions/checkout@v3
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "22"
+      - name: Install dependencies
+        run: npm install
+      - name: Test
+        run: npm run build
